// Validate MoEx clean-room dequant against external oracle fixtures
// (build/fixtures/*, generated by tools/gen_dequant_fixtures.py).
#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "compute/dequant.h"

using namespace moex;

static std::vector<uint8_t> read_bytes(const std::string& p) {
  std::ifstream f(p, std::ios::binary);
  return {std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>()};
}

static gguf::GgmlType parse_type(const std::string& s) {
  using T = gguf::GgmlType;
  if (s == "Q4_K") return T::Q4_K;
  if (s == "Q5_K") return T::Q5_K;
  if (s == "Q6_K") return T::Q6_K;
  if (s == "Q8_0") return T::Q8_0;
  if (s == "F32") return T::F32;
  return T::UNKNOWN;
}

int main(int argc, char** argv) {
  const std::string dir = argc > 1 ? argv[1] : "build/fixtures";
  std::ifstream man(dir + "/manifest.txt");
  if (!man) { std::fprintf(stderr, "no manifest in %s\n", dir.c_str()); return 2; }

  std::string line;
  int fail = 0, total = 0;
  while (std::getline(man, line)) {
    if (line.empty()) continue;
    std::istringstream ss(line);
    std::string name, type;
    uint64_t n, rawlen;
    ss >> name >> type >> n >> rawlen;
    ++total;

    std::vector<uint8_t> raw = read_bytes(dir + "/" + name + ".raw");
    std::vector<uint8_t> refb = read_bytes(dir + "/" + name + ".f32");
    const float* ref = reinterpret_cast<const float*>(refb.data());

    std::vector<float> got(n);
    if (!dequantize_row(parse_type(type), raw.data(), got.data(), n)) {
      std::printf("[FAIL] %s: dequantize_row rejected type %s\n", name.c_str(), type.c_str());
      ++fail;
      continue;
    }

    double max_abs = 0, sum_sq = 0;
    uint64_t worst = 0;
    for (uint64_t i = 0; i < n; ++i) {
      double e = std::fabs((double)got[i] - (double)ref[i]);
      if (e > max_abs) { max_abs = e; worst = i; }
      sum_sq += e * e;
    }
    double rmse = std::sqrt(sum_sq / n);
    // Oracle and clean-room both compute the same integer math on the same
    // bytes; the only divergence source is fp16->f32 and float rounding order.
    // Require near-exact agreement.
    const double TOL = 2e-6;
    bool ok = max_abs <= TOL;
    std::printf("[%s] %-28s %-5s n=%llu max_abs=%.2e rmse=%.2e (got[%llu]=%.6f ref=%.6f)\n",
                ok ? "PASS" : "FAIL", name.c_str(), type.c_str(),
                (unsigned long long)n, max_abs, rmse, (unsigned long long)worst,
                got[worst], ref[worst]);
    if (!ok) ++fail;
  }
  std::printf("\n%d/%d fixtures passed\n", total - fail, total);
  return fail ? 1 : 0;
}
